### ISSUE TITLE
Regarding Prepare the Bunnies' Escape question in google's foobar challenge

### ISSUE THREAD

**Issue by Harshit564** [megha14/Google-foobar-Challanges#1]
I tried it but struck at 2 test cases. Please can u guide me

**Comment by megha14** [comment]
what approach are you using?

**Comment by megha14** [comment]
Find the shortest distance from start node to the destination node (using BFS) by replacing each node having 1 by 0, one by one and save in set/array, then return the minimum from them. Hope this helps.

**Comment by Harshit564** [comment]
thanks for helping I got that.
